### PR TITLE
update dev and staging to v24.2.1-beta.8

### PR DESCRIPTION
**Pull request by afwillia**
PR Checklist:
[ ] Describe and explain your intentions for this change

- don't run the dashboard processing loops in parallel

[ ] Setup pre-commit and run the validators (info in README.md)

### CODE REVIEW

**Comment by milen-sage** [comment]
@afwillia I thought running the dashboard processing loops in parallel was beneficial?

**Comment by afwillia** [comment]
@milen-sage it is, but I am trying to debug an AD issue.

**Comment by milen-sage** [comment]
Ah, I see. Ok - yes, curious if that's the cause. 

But that would have impacted other projects too, no?

**Comment by afwillia** [comment]
I would have thought so, but the demo project has been working fine. Though I wasn't able to get HTAN HMS to load either.

**Pull request merged**
