### PR TITLE
Update to v0.3.9-beta

### PR DESCRIPTION
**Pull request by afwillia**
PR Checklist:
[ ] Describe and explain your intentions for this change
Update the app to v0.3.9-beta
[ ] Setup pre-commit and run the validators (info in README.md)

### CODE REVIEW

**Review by brucehoff — CHANGES_REQUESTED** [review]
"Describe and explain your intentions for this change"

**Comment by afwillia** [comment]
Update the deployment script to use the v0.3.9-beta image of DCA

**Comment by brucehoff** [comment]
> Update the app to v0.3.9-beta

It seems like a poor practice to build the container image from a base image in a personal fork:

https://github.com/Sage-Bionetworks/data_curator/blob/beta-schematic-rest-api/Dockerfile

```
FROM ghcr.io/afwillia/shiny-base:release-1.4
...
```

Is there a reason this is necessary?

**Comment by afwillia** [comment]
It's for development and testing. The base image will be updated for production.

**Comment by brucehoff** [comment]
> It's for development and testing. The base image will be updated for production.

Yes, but wouldn't a better pattern be:

awillams-shiny-base -> awilliams-data_curator-infra -> awilliams-dev-deployment

Sage-Bio-shiny-base -> Sage-Bio-data_curator-infra -> common-dev-deployment

(instead of awillams-shiny-base -> Sage-Bio-data_curator-infra -> common-dev-deployment)
?

Following the former pattern ensures that the code in the 'common repo' (Sage-Bionetworks/*) has always gone through the PR->review->merge QA process.

**Comment by afwillia** [comment]
Under that framework would each developer have their own AWS stack of DCA?

**Comment by afwillia** [comment]
closing this PR to push a different version of the app soon.

**Pull request closed without merging**
